version: 2
jobs:
  build:
    working_directory: /go/src/github.com/YasushiKobayashi/dump
    docker:
      - image: golang:1.11.2
        environment:
          ROOF_ENV: test
          CIRCLE_TEST_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_TEST_ARTIFACTS
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go build -o dump main.go
      - run: $GOPATH/src/github.com/YasushiKobayashi/dump/dump
      - run: go vet ./...
      - run: go test -cover -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go tool cover -html=coverage.txt -o cover.html
      - run: bash <(curl -s https://codecov.io/bash)
      - run: cp cover.html $CIRCLE_TEST_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts
